baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Glitch Report'
theme= "archie"
copyright = "© Zenith Rifle"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About Me"
url = "/about"
weight = 3

[[menu.main]]
name = "Contact Me"
url = "/contacts"
weight = 4
