baseURL = 'https://blog.eason.fr.to/'
languageCode = 'en-us'
title = 'Zenith Rifle'
theme = "lightbi-hugo"
disqusShortname = 'easonli'
enableRobotsTXT = true



[Params.Author]
  name = "Zenith Rifle"
  authorInfo = "Nerdy teenager."
  email = "first@sharecrypt.uk"
  github = "eli32-vlc"


dateFormat = "02 January 2006"


description="Zenith's blog."


showPostImage = true


rss = true
